name: macOS build
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    strategy:
      matrix:
        os:
          - 11
          - 12
    runs-on: macos-${{ matrix.os }}
    name: 'macos-${{ matrix.os }}'
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: |
        mkdir _build
        cd _build && cmake .. -DBUILD_TESTS=ON -DDOWNLOAD_DOCTEST=ON -DBUILD_BENCHMARK=ON -DBUILD_EXAMPLES=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"
    - name: Build
      run: cmake --build _build --verbose
    - name: Testing sequential
      run: cmake --build _build --target xbenchmark --verbose
    - name: Testing xsimd
      run: ${{github.workspace}}/_build/test/test_xsimd
